---
- name: This playbook creates a file
  hosts: webservers
  become: true
  tasks:
          - name: Creating a file
            file:
                    path: /home/vijay/demofile
                    state: touch
