---
- name: This playbook deletes a directory
  hosts: webservers
  become: true
  tasks:
          - name: Deleting a directory
            file:
                    path: /home/vijay/dirA
                    state: absent
