---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks:
          - name: Installing httpd package
            yum:
                    name: httpd
                    state: installed

          - name: Starting a service
            service:
                    name: httpd
                    state: started           
