---
- name: This playbook install packages
  hosts: webservers
  # become: true
  tasks:
          - name: Installing a package
            yum:
                    name: git
                    state: latest
