---
- name: This playbook installs  package
  hosts: webservers
  become: true
  tasks:
  - name: Installing httpd package
    yum: 
      name: httpd 
      state: present
    when: ansible_os_family == "RHEL"

  - name: Starting httpd service
    service:
      name: http-- #error made while writing script,hande the error and continue the execution of rest of the code.
      state: started
    when: ansible_os_family == "RHEL"
    ignore_errors: yes #Error handling

  - name: Installing apache2 package
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Starting apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy:
      src: /home/vijay/index.html
      dest: /var/www/html
      mode: 0666
